import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { ComponentProps } from 'react';
import type { Citation } from '../lib/contracts';
import { Tooltip } from './Tooltip';
import { Badge } from './Badge';

function formatScore(n: number | undefined): string {
  if (typeof n !== 'number' || Number.isNaN(n)) return 'n/a';
  return n.toFixed(3);
}

function resolveCitationLabel(chunkId: string, citations: Citation[]): string {
  const c = citations.find((x) => x.chunk_id === chunkId);
  const title = c?.document_title ?? c?.title ?? 'Untitled document';
  const score = c?.score ?? c?.similarity;
  return `${title}\nchunk: ${chunkId}\nscore: ${formatScore(score)}`;
}

export function MarkdownAnswer({ markdown, citations = [] }: { markdown: string; citations?: Citation[] }) {
  return (
    <div className="prose prose-invert max-w-none prose-slate prose-pre:bg-slate-900/60 prose-pre:border prose-pre:border-slate-800">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          a(props: ComponentProps<'a'>) {
            const href = typeof props.href === 'string' ? props.href : '';
            // Intercept our citation links generated by linkifyCitationMarkers
            if (href.startsWith('#chunk:')) {
              const raw = href.slice('#chunk:'.length);
              const chunkId = decodeURIComponent(raw);
              const label = resolveCitationLabel(chunkId, citations);
              return (
                <Tooltip label={label}>
                  <span className="not-prose inline-flex">
                    <Badge>
                      <span className="text-slate-300">Source</span>
                      <span className="mx-1 text-slate-500">•</span>
                      <span className="font-mono text-slate-200">{chunkId.slice(0, 8)}</span>
                    </Badge>
                  </span>
                </Tooltip>
              );
            }

            // default external link behavior
            return (
              <a
                {...props}
                href={href}
                target={href.startsWith('http') ? '_blank' : props.target}
                rel={href.startsWith('http') ? 'noreferrer' : props.rel}
              />
            );
          },
        }}
      >
        {markdown}
      </ReactMarkdown>
    </div>
  );
}
